
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: ${BADGES_APP_DATASOURCE_URL}
    username: ${BADGES_APP_DATASOURCE_USERNAME}
    password: ${BADGES_APP_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
liquibase:
  change-log: classpath:/liquibase/changes.xml

#security:
#  ldap:
#    enabled: false
#  oauth2:
#    client:
#      clientId: 1822033224766752
#      clientSecret: ...
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me
server:
  port: 1313
  session:
    timeout: 1800
    cookie:
      max-age: 172800
